init
alisolanki/Welcome-to-Open-Source pull request #116
Opened 2023-03-20 22:11 UTC by AryaBait7

lets go

2023-03-21 18:56 UTC, alisolanki requested changes

2023-03-21 18:56 UTC, alisolanki commented on README.md
> +                <a href="https://google.com/">
Please do not change existing contributor's details

2023-03-21 18:56 UTC, alisolanki commented on README.md
> +                    <sub><b>Arya Bait</b></sub>
Please do not change existing contributor's details

2023-03-21 18:56 UTC, alisolanki commented on README.md
> +                    <img src="https://avatars.githubusercontent.com/u/55312000?v=4" width="100px;" alt="Ali Solanki"/>
Please add your own name in alt

2025-03-15 04:34 UTC, tkeefe commented
Please follow the directions.

2025-03-15 04:34 UTC, closed without merging