Abdul Salaam Danish🍉
alisolanki/Welcome-to-Open-Source pull request #137
Opened 2023-03-21 18:46 UTC by AS-Danish

I Added my name to the Contributor List

2023-03-21 19:02 UTC, alisolanki requested changes

2023-03-21 19:02 UTC, alisolanki commented on README.md
> +            <td align="center">
Please add your name to the end of the list

2023-03-21 19:24 UTC, AS-Danish commented
Changes Done

2023-03-25 12:25 UTC, merged

2023-03-25 12:26 UTC, basedharsh commented
> Changes Done

Thanks merged👍