Jackson Contri🍉
alisolanki/Welcome-to-Open-Source pull request #156
Opened 2023-03-22 07:43 UTC by 00jackson

Hey, 
I am Jackson and this is my first open source contribution.

2023-03-24 16:51 UTC, 00jackson commented
Request to merge the pull request. 🍉

2023-03-28 18:03 UTC, alisolanki commented on README.md
> +
Please remove this blank space

2023-03-28 18:04 UTC, alisolanki requested changes

2023-03-28 18:04 UTC, alisolanki commented
Please open a new PR with the changes in place

2023-03-28 18:04 UTC, closed without merging