Update README.md
alisolanki/Welcome-to-Open-Source pull request #1985
Opened 2024-03-29 13:46 UTC by MandoIsGood

You forgot the most important thing (To tell people to subsribe)

2024-03-29 19:45 UTC, thilinaabey commented
Try this repositories if your merge request still haven't got accepted. https://github.com/thilinaabey/Open-Source-Project

2024-04-23 18:51 UTC, StackOverflowIsBetterThanAnyAI requested changes

2024-04-23 18:51 UTC, StackOverflowIsBetterThanAnyAI commented on README.md
> +    <li>Do not forget to like and subsribe for more tech related content!</li>
```suggestion
    <li>Do not forget to like and subscribe for more tech related content!</li>
```

2025-03-22 03:17 UTC, tkeefe commented
Please follow directions.

2025-03-22 03:17 UTC, closed without merging