Jaydeep Edit
alisolanki/Welcome-to-Open-Source pull request #2037
Opened 2024-04-26 18:03 UTC by JaydeepRokade

Some of the information was added to the code

2024-05-01 21:37 UTC, StackOverflowIsBetterThanAnyAI requested changes

2024-05-01 21:37 UTC, StackOverflowIsBetterThanAnyAI commented on README.md
> +                    <sub><b>Jaydeep Rokade</b></sub>
Why did you change that? Please revert if it was for no reason.

2024-05-01 21:37 UTC, StackOverflowIsBetterThanAnyAI commented on README.md
> +                    <sub><b>Sweeti Sharma</b></sub>
Same here: Why did you change that? Please revert if it was for no reason.

2024-05-01 21:37 UTC, StackOverflowIsBetterThanAnyAI commented on README.md
> +                </a>
Please keep your card realistic. The alt attribute and your name should be the same, your github handle is: https://github.com/JaydeepRokade

2025-03-22 03:16 UTC, tkeefe commented
Please follow directions.

2025-03-22 03:16 UTC, closed without merging