Adithyan
alisolanki/Welcome-to-Open-Source pull request #2059
Opened 2024-05-08 14:23 UTC by Adithyanstyle1

Adithyan pull request

2024-05-08 15:47 UTC, StackOverflowIsBetterThanAnyAI requested changes

2024-05-08 15:47 UTC, StackOverflowIsBetterThanAnyAI commented on README.md
> +              <td align="center">
```suggestion
            <td align="center">
```

2024-05-08 15:47 UTC, StackOverflowIsBetterThanAnyAI commented on README.md
> +              <td align="center">
The PR looks good, but the <td> tag is not indented correctly.

2025-03-22 03:16 UTC, tkeefe commented
Please follow directions.

2025-03-22 03:16 UTC, closed without merging