My First contribution with an open source repo
alisolanki/Welcome-to-Open-Source pull request #2097
Opened 2024-05-22 09:30 UTC by BaraSedih11

Please Accept this contriution

2024-05-23 17:47 UTC, StackOverflowIsBetterThanAnyAI requested changes

2024-05-23 17:47 UTC, StackOverflowIsBetterThanAnyAI commented on README.md
> +                    <img src="https://avatars.githubusercontent.com/u/98843912?v=4" width="100px;" alt="Shubham Raut"/>
```suggestion
                    <img src="https://avatars.githubusercontent.com/u/98843912?v=4" width="100px;" alt="Bara Al-Sedih"/>
```

2024-05-24 21:15 UTC, BaraSedih11 reviewed
You're correct, my mistake. I updated the duplication in the followed commit

2024-05-25 08:00 UTC, StackOverflowIsBetterThanAnyAI approved these changes

2025-03-23 03:58 UTC, tkeefe commented
Please follow directions.

2025-03-23 03:58 UTC, closed without merging