Ansh ✨
alisolanki/Welcome-to-Open-Source pull request #2145
Opened 2024-06-09 22:09 UTC by Anshx-xx

This is my first time creating a pull request !

2024-06-10 19:43 UTC, StackOverflowIsBetterThanAnyAI requested changes

2024-06-10 19:43 UTC, StackOverflowIsBetterThanAnyAI commented on README.md
> +                    <sub><b>Shubham Raut</b></sub>
```suggestion
                    <sub><b>Ansh Somaiya</b></sub>
```

2024-06-11 07:35 UTC, StackOverflowIsBetterThanAnyAI approved these changes

2025-03-19 00:09 UTC, tkeefe commented
Please follow the directions.

2025-03-19 00:09 UTC, closed without merging