Rhap-Rhap/Melchor
alisolanki/Welcome-to-Open-Source pull request #2151
Opened 2024-06-11 04:57 UTC by Ciupao

Adding my name to contributer list

2024-06-11 19:46 UTC, StackOverflowIsBetterThanAnyAI requested changes

2024-06-11 19:46 UTC, StackOverflowIsBetterThanAnyAI commented on README.md
> +</td>
You added the same information twice.
```suggestion
```

2024-06-11 19:46 UTC, StackOverflowIsBetterThanAnyAI commented on README.md
> +</td>
Please indent correctly.

2024-06-11 19:46 UTC, StackOverflowIsBetterThanAnyAI commented on README.md
> +        <sub><b>Rhap-Rhap/Melchor</b></sub>
```suggestion
        <sub><b>Ciupao</b></sub>
```

2025-03-19 00:09 UTC, tkeefe commented
Please follow the directions.

2025-03-19 00:09 UTC, closed without merging