Jayson🤖
alisolanki/Welcome-to-Open-Source pull request #2155
Opened 2024-06-11 15:37 UTC by jaysonarabia

Adding my name to the contributor list | BSIT 2-3

2024-06-11 19:50 UTC, StackOverflowIsBetterThanAnyAI requested changes

2024-06-11 19:50 UTC, StackOverflowIsBetterThanAnyAI commented on README.md
> +                    <sub><b>Jayson Arabia</b></sub>
Please revert this change:
```suggestion
                    <sub><b>Harsh Pandey</b></sub>
```

2024-06-11 19:50 UTC, StackOverflowIsBetterThanAnyAI commented on README.md
> +                    <img src="https://avatars.githubusercontent.com/u/113113910?v=4" width="100px;" alt="Harsh Pandey"/>
Please revert this change:
```suggestion
                    <img src="https://avatars.githubusercontent.com/u/90195370?v=4" width="100px;" alt="Harsh Pandey"/>
```

2025-03-19 00:10 UTC, tkeefe commented
Please follow the directions.

2025-03-19 00:10 UTC, closed without merging