mariai756
alisolanki/Welcome-to-Open-Source pull request #2171
Opened 2024-06-12 14:11 UTC by mariai756

2024-06-12 14:12 UTC, mariai756 commented
maria

2024-06-12 17:43 UTC, StackOverflowIsBetterThanAnyAI requested changes

2024-06-12 17:43 UTC, StackOverflowIsBetterThanAnyAI commented on README.md
> +                    <img src="https://avatars.githubusercontent.com/u/172351485?v=4" width="100px;" alt="Shubham Raut"/>
```suggestion
                    <img src="https://avatars.githubusercontent.com/u/172351485?v=4" width="100px;" alt="Maria Ibita"/>
```

2025-03-19 00:11 UTC, tkeefe commented
Please follow the directions.

2025-03-19 00:11 UTC, closed without merging