Kishore
alisolanki/Welcome-to-Open-Source pull request #2206
Opened 2024-06-20 19:19 UTC by Kishore007raj

Journey of my first contribution

2024-06-21 10:34 UTC, StackOverflowIsBetterThanAnyAI requested changes
Hey, please do not overwrite already existing content. Instead, copy another user's card and edit it with your personal information.

2024-06-21 13:07 UTC, Kishore007raj commented
> Hey, please do not overwrite already existing content. Instead, copy another user's card and edit it with your personal information.

ok got it

2024-06-21 13:49 UTC, StackOverflowIsBetterThanAnyAI approved these changes
perfect 👍

2025-03-22 03:12 UTC, tkeefe commented
Please follow directions.

2025-03-22 03:12 UTC, closed without merging