Adding my name to contributor list
alisolanki/Welcome-to-Open-Source pull request #2223
Opened 2024-06-24 10:46 UTC by thishi-r156

2024-06-24 16:04 UTC, StackOverflowIsBetterThanAnyAI requested changes

2024-06-24 16:04 UTC, StackOverflowIsBetterThanAnyAI commented on README.md
> +</table>
```suggestion
</table>
```

2024-06-24 16:04 UTC, StackOverflowIsBetterThanAnyAI commented on README.md
> +                    <img src="https://avatars.githubusercontent.com/u/80586776?s=400&v=4" width="100px;" alt="Shubham Raut"/>
```suggestion
                    <img src="https://avatars.githubusercontent.com/u/80586776?s=400&v=4" width="100px;" alt="Thishi"/>
```

2025-03-22 03:12 UTC, tkeefe commented
Please follow directions.

2025-03-22 03:12 UTC, closed without merging