Huzaifa Fiaz
alisolanki/Welcome-to-Open-Source pull request #2324
Opened 2024-08-01 07:45 UTC by huzaifaawan699

Adding my name to the contributor list

2024-08-03 12:18 UTC, StackOverflowIsBetterThanAnyAI requested changes

2024-08-03 12:18 UTC, StackOverflowIsBetterThanAnyAI commented on README.md
> +                <a href="https://github.com/account">
```suggestion
                <a href="https://github.com/huzaifaawan699">
```

2024-08-03 12:18 UTC, StackOverflowIsBetterThanAnyAI commented on README.md
> +                    <img src="https://avatars.githubusercontent.com/u/119066287?s=400&u=1a10d9b5d6e39c93cf832bd359002628495daa1b&v=4" width="100px;" alt="Harsh Pandey"/>
```suggestion
                    <img src="https://avatars.githubusercontent.com/u/119066287?s=400&u=1a10d9b5d6e39c93cf832bd359002628495daa1b&v=4" width="100px;" alt="Huzaifa Fiaz"/>
```

2025-03-19 00:04 UTC, tkeefe commented
Please follow the directions.

2025-03-19 00:04 UTC, closed without merging