Caspian AKA Nouman 🍉
alisolanki/Welcome-to-Open-Source pull request #2613
Opened 2024-11-06 14:33 UTC by Nouman-wp

Added Myself as a Contributor

2024-11-06 14:48 UTC, ekrishnachaitanya2004 commented
Hey everyone! 👋 I noticed there are a lot of pull requests pending here, and it seems the admin might be offline. If you’re looking for active projects to contribute to, I’d love for you to check out [Dev Blog](https://github.com/Snakes-n-Networks/Dev-blogs)! It’s a platform I created for developers to share tutorials, project showcases, and insights, and we’re open to contributions. Whether you’re interested in web development, cybersecurity, or programming tips, there’s a place for you.

Come join us and make your mark – your contributions are welcome!

This is friendly, and it offers a good alternative for contributors looking to get started in open source.

2024-11-09 13:21 UTC, StackOverflowIsBetterThanAnyAI requested changes

2024-11-09 13:21 UTC, StackOverflowIsBetterThanAnyAI commented on README.md
> +                    <img src="https://avatars.githubusercontent.com/u/168581465?v=4" width="100px;" alt="Kaone Keboetseng"/>
```suggestion
                    <img src="https://avatars.githubusercontent.com/u/168581465?v=4" width="100px;" alt="Mujeeb Nouman"/>
```

2024-11-09 21:24 UTC, StackOverflowIsBetterThanAnyAI approved these changes

2024-12-15 08:42 UTC, closed without merging