Master
alisolanki/Welcome-to-Open-Source pull request #2617
Opened 2024-11-07 08:50 UTC by rashid2002

2024-11-07 08:50 UTC, rashid2002 reviewed
rashid

2024-11-09 13:20 UTC, StackOverflowIsBetterThanAnyAI requested changes

2024-11-09 13:20 UTC, StackOverflowIsBetterThanAnyAI commented on README.md
> +                    <img src="https://avatars.githubusercontent.com/u/92138079?v=4" width="100px;" alt="Kaone Keboetseng"/>
```suggestion
                    <img src="https://avatars.githubusercontent.com/u/92138079?v=4" width="100px;" alt="Mohd Rashid Ansari"/>
```

2025-03-22 03:12 UTC, tkeefe commented
Please follow directions.

2025-03-22 03:12 UTC, closed without merging