VaradScript🍉
alisolanki/Welcome-to-Open-Source pull request #2622
Opened 2024-11-09 05:45 UTC by VaradScript

adding my contro🍉

2024-11-09 13:19 UTC, StackOverflowIsBetterThanAnyAI requested changes

2024-11-09 13:19 UTC, StackOverflowIsBetterThanAnyAI commented on README.md
> +             <td align="center">
```suggestion
            <td align="center">
```

2024-11-09 13:19 UTC, StackOverflowIsBetterThanAnyAI commented on README.md
> +                    <img src="[[https://avatars.githubusercontent.com/u/115893185?v=4]](https://avatars.githubusercontent.com/u/108749445?v=4)" width="100px;" alt="varadScript"/>
```suggestion
                    <img src="https://avatars.githubusercontent.com/u/108749445?v=4" width="100px;" alt="varadScript"/>
```

2025-06-22 17:12 UTC, KHC2003 commented
Hey, just saw your PR here — cool stuff. I ended up checking out this repo after someone mentioned it, and while digging through things I figured I’d drop a quick note. I recently joined this open dev community called [Krypto Hashers Community](https://github.com/Krypto-Hashers-Community) — it’s just a bunch of devs building random things, experimenting, sharing ideas, that kind of vibe. Nothing super formal, just people doing cool stuff together. Thought you might be interested if you’re into open source or tinkering on side projects. Feel free to check it out if you’re curious.

2025-06-25 16:11 UTC, VaradScript commented
Hey @KHC2003,

Thanks for checking out the project and reaching out! The Cyzno Haihen Community sounds like a great space for creators and open-source enthusiasts. I'd definitely be interested in learning more about it.

Could you share:
1. Any links to the community's platforms (GitHub/Discord/etc.)?
2. What kind of projects people are currently working on?

Also, regarding the PR - just saw the status change. Everything looks merge-ready on my end. Let me know if you need any adjustments before proceeding.

Appreciate the connection!

2025-06-25 16:11 UTC, closed without merging