Darshit 🍉
alisolanki/Welcome-to-Open-Source pull request #2629
Opened 2024-11-11 14:41 UTC by Darshit-Thakkar

adding my name to contributer list. this is my first open source contribution.

2024-11-11 17:14 UTC, StackOverflowIsBetterThanAnyAI requested changes

2024-11-11 17:14 UTC, StackOverflowIsBetterThanAnyAI commented on README.md
> +                    <img src="https://github.com/account" width="100px;" alt="Darshit Thakkar"/>
```suggestion
                    <img src="https://github.com/Darshit-Thakkar" width="100px;" alt="Darshit Thakkar"/>
```

2024-11-13 14:08 UTC, Darshit-Thakkar commented
merage my pull request.

2024-11-14 08:16 UTC, StackOverflowIsBetterThanAnyAI approved these changes

2025-04-23 05:54 UTC, closed without merging