Mohammed Raiyan
alisolanki/Welcome-to-Open-Source pull request #2635
Opened 2024-11-13 09:48 UTC by mohammedraiyan1

I want to add my name to the contributor's list.

2024-11-14 09:48 UTC, StackOverflowIsBetterThanAnyAI requested changes

2024-11-14 09:48 UTC, StackOverflowIsBetterThanAnyAI commented on README.md
> +                     width="100px;" alt="Mohammed Raiyan"/>
```suggestion
            <td align="center">
                <a href="https://github.com/mohammedraiyan1">
                    <img src="https://avatars.githubusercontent.com/u/169655337?v=4" width="100px;" alt="Mohammed Raiyan"/>
```

2024-11-14 09:48 UTC, StackOverflowIsBetterThanAnyAI commented on README.md
> +                     width="100px;" alt="Mohammed Raiyan"/>
indent correctly
width and alt attribute do not have to be in an extra line

2025-03-18 23:49 UTC, tkeefe commented
Please follow the directions.

2025-03-18 23:49 UTC, closed without merging