my first open contribution
alisolanki/Welcome-to-Open-Source pull request #2659
Opened 2024-11-22 13:55 UTC by amitrawani07

2024-11-22 22:24 UTC, StackOverflowIsBetterThanAnyAI requested changes

2024-11-22 22:24 UTC, StackOverflowIsBetterThanAnyAI commented on README.md
> +                    <img src="https://img.freepik.com/premium-photo/cute-handsome-anime-boy-blue-light_675932-435.jpg" width="100px;" alt="Amit"/>
```suggestion
                    <img src="https://avatars.githubusercontent.com/u/178783034?v=4" width="100px;" alt="Amit"/>
```

2024-11-22 22:24 UTC, StackOverflowIsBetterThanAnyAI commented on README.md
> +        <td align="center">
```suggestion
            <td align="center">
```

2024-11-23 08:08 UTC, StackOverflowIsBetterThanAnyAI approved these changes

2025-03-18 23:50 UTC, closed without merging

2025-03-18 23:50 UTC, tkeefe commented
Please follow the directions.