adding my github and photo
alisolanki/Welcome-to-Open-Source pull request #2718
Opened 2024-12-06 06:22 UTC by Abiral-2724

2024-12-08 09:59 UTC, StackOverflowIsBetterThanAnyAI requested changes

2024-12-08 09:59 UTC, StackOverflowIsBetterThanAnyAI commented on README.md
> +                    <img src="https://avatars.githubusercontent.com/u/134861989?v=4" width="100px;" alt="Kaone Keboetseng"/>
```suggestion
                    <img src="https://avatars.githubusercontent.com/u/134861989?v=4" width="100px;" alt="Abiral jain"/>
```

2024-12-08 09:59 UTC, StackOverflowIsBetterThanAnyAI commented on README.md
> +             <td align="center">
```suggestion
            <td align="center">
```

2025-03-18 23:52 UTC, tkeefe commented
Please follow the directions.

2025-03-18 23:52 UTC, closed without merging