Harsh Bhanushali
alisolanki/Welcome-to-Open-Source pull request #2723
Opened 2024-12-07 06:25 UTC by Harsh772005

this is my first contribution on open - source project.

2024-12-08 10:02 UTC, StackOverflowIsBetterThanAnyAI requested changes
you inserted your code one line too early

2024-12-08 10:02 UTC, StackOverflowIsBetterThanAnyAI commented on README.md
> +            </td>
```suggestion
            </td>
            <td align="center">
                <a href="https://github.com/Harsh772005">
                    <img src="https://avatars.githubusercontent.com/u/120744063?v=4" width="100px;" alt="Harsh Bhanushali"/>
                    <br />
                    <sub><b>Harsh Bhanushali</b></sub>
                </a>
```

2024-12-08 18:45 UTC, StackOverflowIsBetterThanAnyAI approved these changes

2025-03-22 03:11 UTC, tkeefe commented
Please follow directions.

2025-03-22 03:11 UTC, closed without merging