Wingchee 🍉
alisolanki/Welcome-to-Open-Source pull request #2767
Opened 2024-12-14 10:33 UTC by wingcheew

Adding my name to contributer list

2024-12-15 08:29 UTC, StackOverflowIsBetterThanAnyAI requested changes

2024-12-15 08:29 UTC, StackOverflowIsBetterThanAnyAI commented on README.md
> +            </td>
```suggestion
            <a href="https://github.com/wingcheew">
                <img src="https://avatars.githubusercontent.com/u/191438807?v=4" width="100px;" alt="Wingchee W"/>
                <br />
                <sub><b>Wingchee W</b></sub>
            </a> 
        </td>
```

2024-12-15 14:07 UTC, StackOverflowIsBetterThanAnyAI approved these changes

2025-03-24 21:59 UTC, tkeefe commented
Please fix merge conflict.

2025-03-24 21:59 UTC, closed without merging