Karan 🍉
alisolanki/Welcome-to-Open-Source pull request #2819
Opened 2024-12-24 16:28 UTC by karan1600

Did my first git pull request

2024-12-24 20:15 UTC, StackOverflowIsBetterThanAnyAI requested changes

2024-12-24 20:15 UTC, StackOverflowIsBetterThanAnyAI commented on README.md
> +                <a href="https://github.com/settings/profile">
```suggestion
                <a href="https://github.com/karan1600">
```

2024-12-24 20:15 UTC, StackOverflowIsBetterThanAnyAI commented on README.md
> +                    <img src="https://avatars.githubusercontent.com/u/110373674?s=400&u=47cc070ba8637beefe55a1d892cce706f35a5723&v=4" width="100px;" alt="Karan"/>
```suggestion
                    <img src="https://avatars.githubusercontent.com/u/110373674?s=400&u=47cc070ba8637beefe55a1d892cce706f35a5723&v=4" width="100px;" alt="Karan Kumar"/>
```

2025-03-23 22:37 UTC, tkeefe commented
Fix merge conflict.

2025-03-23 22:37 UTC, closed without merging