🍉Vishal
alisolanki/Welcome-to-Open-Source pull request #487
Opened 2023-04-03 16:08 UTC by vishalsingh2972

Adding my name to the contributor list !

2023-04-03 20:12 UTC, alisolanki requested changes

2023-04-03 20:12 UTC, alisolanki commented on .idea/vcs.xml
delete this file

2023-04-03 20:12 UTC, alisolanki commented on .idea/modules.xml
delete this file

2023-04-03 20:12 UTC, alisolanki commented on .idea/misc.xml
delete this file

2023-04-03 20:12 UTC, alisolanki commented on .idea/.gitignore
make sure to not change this file

2023-04-05 15:10 UTC, vishalsingh2972 commented
@alisolanki cannot make changes as deleted the previous fork, creating new PR....please accept that

2023-04-05 15:29 UTC, vishalsingh2972 commented on .idea/Welcome-to-Open-Source.iml
unable to commit if deleting this so kept this deleted the rest, please accept the new PR!

2023-04-05 15:38 UTC, closed without merging